name = "sentinel-nexus-gateway"
main = "index.js"
compatibility_date = "2026-03-19"
account_id = "22202ff07e559347483b0526ded1fd31"

[vars]
# The salt used for SHA-256 token generation. 
# SECRET_SALT = "QmffEhFM1xDdmHpPbZODELNZmN12VimMRBJlbM2oN4=" 

[[kv_namespaces]]
binding = "NEXUS_STATE"
id = "601fd807e634495c875b153f1344ae3c"

[triggers]
crons = [] # No crons needed; this is a reactive API
